### ISSUE TITLE
Investigate Calculation of Run-out when x/<keeper-symbol>y if the y's name is read correctly.

### ISSUE THREAD

**Issue by uday13** [vakeeel/fantasy-ipl#1]
# RPS vs RCB

MK Tiwary   ---> run out (Kohli/†Jadhav)

Reading the first name  and adding the 5 points to the 1st player(KOHLI) and 0 points to the 2nd player(JADHAV) 

As per script : 
```
Our team: 238
Opposing team: 117
TOTAL : 121
```

Calculated Totals  : 
```
Our team: 235.5
Opposing team: 119.5
TOTAL : 121
```

TOTAL's still correct.

**Comment by vakeeel** [comment]
Fixed @uday13
