### ISSUE TITLE
Investigate Individual Points Calculator 

### ISSUE THREAD

**Issue by uday13** [vakeeel/fantasy-ipl#2]
# RCB vs RPS

As per Script : 
```
V Kohli||5|
S Aravind||20|
AF Milne||20|
Mandeep Singh||10|
AB de Villiers|||
KM Jadhav|||
```

Calculated Points : 
```
V Kohli - 7.5
S Aravind - 45
AF Milne - 45
Mandeep Singh - 5
AB de Villiers - 5
KM Jadhav -2.5
```
Investigate Individual Score Calculator
 
TOTAL's not an issue even with difference in Individual Points.

**Comment by vakeeel** [comment]
@uday13 how did he have 0.5? If two fielders are involved does each player get 2.5?

**Comment by vakeeel** [comment]
Fixed @uday13.
