### ISSUE TITLE
Investigate Fielding Score

### ISSUE THREAD

**Issue by uday13** [vakeeel/fantasy-ipl#3]
##  RCB vs  RPS
**Opposing Team**
```
Player               Batting Score        Fielding Score       Total Score         
Mandeep Singh        0                    10                   10                  
AB de Villiers       29                   0                    29  
```
From Scorecard : http://www.espncricinfo.com/indian-premier-league-2017/engine/match/1082605.html 
```
ABD : 5 points
Mandeep : 5 points
``` 
ABD's name in the Scorecard for catch is 'de Villiers' instead of Input 'AB de Villiers' so I think it's not finding the player and adding the points to the previous player.

**Comment by vakeeel** [comment]
The latest commit should have the fix @uday13.

**Comment by uday13** [comment]
The latest commit e9f49839c21af27e32cb1ad991e2cf96a3744128 also gave the same result.
```
Player               Batting Score        Fielding Score       Total Score         
Mandeep Singh        0                    10                   10                  
AB de Villiers       29                   0                    29 
```

**Comment by vakeeel** [comment]
Fixed the issue.
